name: Use GitHub Secret

on:
  push:

jobs:
  use-secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use the secret
        run: |
          echo "The secret is \${{ secrets.SECRET }}"
        shell: bash
