name: Safe Secret Check

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Verify Secret Syntax
        run: echo "The secret is \${{ secrets.SECRET }}"

      - name: Verify Secret Syntax
        run: echo "The secret is {{ secrets.SECRET }}"
        
